### ISSUE TITLE
Please make a LICENSE file

### ISSUE THREAD

**Issue by alexsch01** [Lunarixus/kernel_devices_google_bluejay#1]
It will hopefully get people to help you working on this kernel modification

**Comment by Lunarixus** [comment]
Closing this issue as the license is in the header of the files and are as per Google's original repo

https://android.googlesource.com/kernel/devices/google/bluejay/+/refs/tags/android-13.0.0_r0.49

**Comment by theVakhovskeIsTaken** [comment]
> It will hopefully get people to help you working on this kernel modification

![istockphoto-1175673630-612x612.jpg](https://user-images.githubusercontent.com/97450182/207231566-8280f75f-dd0f-40da-932f-d9b4eddba1ad.jpg)
